version: '3.1'

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./init.sql:/data/application/init.sql
    command: [
      '--init-file',
      '/data/application/init.sql',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: housing
  housing:
    build: .
    container_name: housing
    ports:
      - "8080:8080"
    environment:
      MYSQL_DB_URL: "jdbc:mysql://db:3306/housing?autoReconnect=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
      MYSQL_DB_USER: root
      MYSQL_DB_PASSWORD: root
    depends_on:
      - db
